---
- name: Create user's bin dir if it doesn't already exist
  delegate_to: "{{ item }}"
  file:
    path: "{{ config_info.user_parent_home_dir }}/{{ config_info.test_user }}/bin"
    mode: "0755"
    state: directory
  with_items:
    - "{{ sys1 }}"
    - "{{ sys2 }}"

- name: Copy ssh key setup tools
  delegate_to: "{{ sys1 }}"
  copy:
    src: "{{ config_info.local_run_dir }}/bin/{{item}}"
    dest: "{{ config_info.user_parent_home_dir }}/{{ config_info.test_user }}/bin/{{ item }}"
    mode: "0755"
  with_items:
    - ssh_net_setup
    - ssh_net_copy

- name: Copy ssh key setup tools
  delegate_to: "{{ sys2 }}"
  copy:
    src: "{{ config_info.local_run_dir }}/bin/{{item}}"
    dest: "{{ config_info.user_parent_home_dir }}/{{ config_info.test_user }}/bin/{{ item }}"
    mode: "0755"
  with_items:
    - ssh_net_setup
    - ssh_net_copy


- name: Create root .ssh directory
  delegate_to: "{{ item }}"
  become: yes
  file:
    path: /root/.ssh
    state: directory
    mode: "0700"
  with_items:
    - "{{ sys1 }}"
    - "{{ sys2 }}"

- name: Run the script to set up our ssh key
  delegate_to: "{{ item }}"
  become: yes
  command: "{{ config_info.user_parent_home_dir }}/{{ config_info.test_user }}/bin/ssh_net_setup"
  with_items:
    - "{{ sys1 }}"
    - "{{ sys2 }}"

- name: ssh key exchange
  include_role:
    name: ssh_key_exchange_aws
  vars:
    sys_1: "{{ sys1 }}"
    sys_2: "{{ sys2 }}"
