repository_type: git_tag
location:  https://gitlab.cee.redhat.com/dvalin
reboot_system: "no"
test_run_from: "remote"
version: v1.0
test_grouping: verify
os_supported: verify
repo_file: uperf.tar
rhel_pkgs: lksctp-tools-devel
ubuntu_pkgs: libsctp-dev,lksctp-toolnet-tools
amazon_pkgs: lksctp-tools-devel
storage_required: "yes"
network_required: "no"
pbench_required: "no"
pbench_local_results: "no"
java_required: "no"
archive_results: "yes"
test_script_to_run: verify.sh
test_specific: ""
upload_extra: "none"
post_script: "none"
pre_setup: "none"
