---
#
# Create the networks and connect the systems.
#

- name: include dynamic info
  include_vars:
    file: "{{ working_dir }}/ansible_run_vars.yml"
    name: dyn_data


#
# Report public ip if we have public as the network
# 
- name: Report public ip
  block:
  - name: set server ip
    lineinfile:
      path: "{{ working_dir }}/ansible_run_vars.yml"
      line: "ct_uperf_server_ip: {{ dyn_data.test_hostname }}"
  - name: set server ip
    lineinfile:
      path: "{{ working_dir }}/ansible_run_vars.yml"
      line: "ct_uperf_client_list: {{ dyn_data.net_hostname }}"
  - name: add net hostname
    add_host:
      name: "{{ dyn_data.net_hostname }}"
      groups: test_group
      ansible_user: "{{ config_info.test_user }}"
      ansible_ssh_private_key_file: "{{ config_info.ssh_key }}"
  when: config_info.cloud_numb_network_type == "public"
