---
# tasks file for roles/ssh_key_exchange
- name: SSH KeyGen command
  delegate_to: "{{ item }}"
  become: yes
  shell: > 
    ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
    creates="~/.ssh/id_rsa"
  with_items:
    - "{{ sys_1 }}"
    - "{{ sys_2 }}"

- name: Fetch the keyfile from one server to another
  delegate_to: "{{ item }}"
  become: yes
  fetch:
    src: "~/.ssh/id_rsa.pub"
    dest: "buffer/{{item}}-id_rsa.pub"
    flat: yes
  with_items:
    - "{{ sys_1 }}"
    - "{{ sys_2 }}"

- name: Copy the key add to authorized_keys using Ansible module
  delegate_to: "{{ sys_1 }}"
  become: yes
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file','buffer/{{ sys_2 }}-id_rsa.pub')}}"

- name: Copy the key add to authorized_keys using Ansible module
  delegate_to: "{{ sys_2 }}"
  become: yes
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file','buffer/{{ sys_1 }}-id_rsa.pub')}}"
